spring:
  application:
    name: google-cloud-storage
  cloud:
    gcp:
      project-id: lofty-root-378503

management:
  endpoints:
    web:
      exposure:
        include: health, info

gcp:
  storage:
    gcs-prefix: gs://
    bucket:
      batch-upload-prefix: batch_uploads/
      name: jm_lofty-root-cmek-test
