spring:
  application:
    name: case-study-1
  batch:
    jdbc:
      initialize-schema: always  # Ensures Spring Batch schema is created on startup.
#    job:
#      enabled: false # Disable automatic job execution on startup
  cloud:
    gcp:
      project-id: lofty-root-378503
    stream:
      bindings:
        ingest-in-0:
          destination: ${gcp.pubsub.topic.name}
          content-type: text/plain
          group: ${gcp.pubsub.subscription.name}
      gcp:
        pubsub:
          bindings:
            input-in-0:
              consumer:
                ack-mode: MANUAL
  test:
    database:
      replace: none # Prevents Spring Boot from replacing the datasource with an in-memory database during tests.
  security:
    user:
      name: admin
      password: admin123
  datasource:
    url: jdbc:postgresql://localhost:5432/session_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always  # Ensures schema.sql runs on startup (use 'never' in production).
      platform: postgres  # Prevents Hibernate from overriding the jsonb data type with varchar data type.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  main:
#    allow-bean-definition-overriding: true

gcp:
  storage:
    gcs-prefix: gs://
    bucket:
      batch-upload-prefix: batch_uploads/
      name: jm_lofty-root-cmek-test

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  jobs:
    enabled: true
